[package]
name = "egglog_syntax"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
sexp = "1.1.4"
syn = { version = "1.0", features = ["full"] }
egglog = { git = "https://github.com/pbonh/egglog.git" }
